dependencies {
    compileOnly(commonLibs.acf)
    compileOnly(commonLibs.paper)
    compileOnly(commonLibs.protocollib)
    compileOnly(commonLibs.nbtapi)
    compileOnly(commonLibs.taskchain)
    compileOnly(commonLibs.mythicmobs)
    compileOnly(commonLibs.springdatamongodb)
    compileOnly(commonLibs.mongodbdrivercore)
    compileOnly(commonLibs.mongodbdriversync)
    compileOnly(commonLibs.jedis)
    compileOnly(commonLibs.luckperms)
    compileOnly(project(":Projects:Database"))
    compileOnly(project(":Projects:Common"))
}