name: RunicItems
description: Runic Realms Items Plugin, by Excel
version: 1.0
main: com.runicrealms.plugin.runicitems.RunicItems
api-version: 1.16
depend:
  - NBTAPI
  - RunicDatabase
  - RunicCommon
  - ProtocolLib
  - MythicMobs
  - RunicRestart
  - ModelEngine
  - HolographicDisplays